---
language: python
python: "2.7"
before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible
  - "echo '[defaults]' > ansible.cfg"
  - "echo 'roles_path = ../' >> ansible.cfg"

script:
  - "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local"
  - "zsh &"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
